// Auto-generated by `backend/scripts/deploy.js`.
// If you redeploy, this JSON is overwritten with latest addresses/ABIs.
import generated from "./contracts.generated.json";

export const ADDRESSES = generated?.addresses;
export const KYC_ABI = generated?.abi?.KYC;
export const CROWDFUNDING_ABI = generated?.abi?.CROWDFUNDING;

